import React, { useState } from 'react';

const ReportGenerator = ({ resultData }) => {
  const [language, setLanguage] = useState('english');

  // Translations
  const translations = {
    english: {
      title: 'Crop Yield Analysis Report',
      generatedOn: 'Generated on:',
      farmDetails: 'Farm Details',
      cropType: 'Crop Type',
      location: 'Location',
      farmArea: 'Farm Area',
      sowingDate: 'Sowing Date',
      weatherConditions: 'Weather Conditions',
      temperature: 'Temperature',
      humidity: 'Humidity',
      weatherDescription: 'Weather Description',
      yieldPredictions: 'Yield Predictions',
      predictedYield: 'Predicted Yield',
      totalProduction: 'Total Production',
      productionPerSqm: 'Production per m²',
      recommendations: 'Recommendations',
      footer: 'Generated by AI Crop Prediction System',
      reportId: 'Report ID:',
      parameter: 'Parameter',
      value: 'Value',
      metric: 'Metric'
    },
    hindi: {
      title: 'फसल उत्पादन विश्लेषण रिपोर्ट',
      generatedOn: 'तैयार की गई:',
      farmDetails: 'खेत का विवरण',
      cropType: 'फसल का प्रकार',
      location: 'स्थान',
      farmArea: 'खेत का क्षेत्रफल',
      sowingDate: 'बुआई की तारीख',
      weatherConditions: 'मौसम की स्थिति',
      temperature: 'तापमान',
      humidity: 'नमी',
      weatherDescription: 'मौसम का विवरण',
      yieldPredictions: 'उत्पादन पूर्वानुमान',
      predictedYield: 'अनुमानित उत्पादन',
      totalProduction: 'कुल उत्पादन',
      productionPerSqm: 'प्रति वर्ग मीटर उत्पादन',
      recommendations: 'सुझाव',
      footer: 'कृषि AI पूर्वानुमान सिस्टम द्वारा तैयार',
      reportId: 'रिपोर्ट आईडी:',
      parameter: 'पैरामीटर',
      value: 'मान',
      metric: 'मेट्रिक'
    }
  };

  const t = translations[language];

  const generatePDFReport = async () => {
    try {
      // Dynamic import to avoid bundling issues
      const jsPDF = (await import('jspdf')).default;
      const autoTable = (await import('jspdf-autotable')).default;

      const doc = new jsPDF();
      const currentDate = new Date().toLocaleDateString();

      // Header (NO EMOJIS)
      doc.setFontSize(20);
      doc.setTextColor(34, 139, 34); // Green color
      doc.text(t.title, 20, 25);
      
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text(`${t.generatedOn} ${currentDate}`, 20, 35);
      
      // Farm Details Section (NO EMOJIS)
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text(t.farmDetails, 20, 50);
      
      const farmDetails = [
        [t.cropType, resultData.crop_name || 'N/A'],
        [t.location, resultData.location || 'N/A'],
        [t.farmArea, `${resultData.area || 0} m²`],
        [t.sowingDate, resultData.sowing_date || 'N/A'],
      ];
      
      autoTable(doc, {
        startY: 55,
        head: [[t.parameter, t.value]],
        body: farmDetails,
        theme: 'striped',
        headStyles: { fillColor: [34, 139, 34] },
        margin: { left: 20 },
      });

      // Weather Conditions (NO EMOJIS)
      let currentY = doc.lastAutoTable.finalY + 15;
      doc.setFontSize(16);
      doc.text(t.weatherConditions, 20, currentY);
      
      const weatherData = [
        [t.temperature, `${resultData.weather?.temperature || 'N/A'} °C`],
        [t.humidity, `${resultData.weather?.humidity || 'N/A'} %`],
        [t.weatherDescription, resultData.weather?.description || 'N/A'],
      ];
      
      autoTable(doc, {
        startY: currentY + 5,
        head: [[t.parameter, t.value]],
        body: weatherData,
        theme: 'striped',
        headStyles: { fillColor: [52, 152, 219] },
        margin: { left: 20 },
      });

      // Predictions & Results (NO EMOJIS)
      currentY = doc.lastAutoTable.finalY + 15;
      doc.setFontSize(16);
      doc.text(t.yieldPredictions, 20, currentY);
      
      const predictedYield = resultData.predicted_yield_kgha || 0;
      const totalProduction = resultData.total_production_tonnes || 0;
      
      const predictions = [
        [t.predictedYield, `${predictedYield.toFixed(2)} kg/ha`],
        [t.totalProduction, `${totalProduction.toFixed(2)} tonnes`],
        [t.productionPerSqm, `${(totalProduction * 1000 / (resultData.area || 1)).toFixed(3)} kg/m²`],
      ];
      
      autoTable(doc, {
        startY: currentY + 5,
        head: [[t.metric, t.value]],
        body: predictions,
        theme: 'striped',
        headStyles: { fillColor: [231, 76, 60] },
        margin: { left: 20 },
      });

      // Recommendations (NO EMOJIS)
      if (resultData.recommendations && resultData.recommendations.length > 0) {
        currentY = doc.lastAutoTable.finalY + 15;
        doc.setFontSize(16);
        doc.text(t.recommendations, 20, currentY);
        
        doc.setFontSize(11);
        let recY = currentY + 10;
        
        resultData.recommendations.forEach((rec, index) => {
          // Remove ALL emojis and special characters for PDF
          const cleanRec = rec.replace(/[^\w\s:.-]/g, '').trim();
          
          // Split long recommendations into multiple lines
          const splitText = doc.splitTextToSize(`${index + 1}. ${cleanRec}`, 170);
          doc.text(splitText, 20, recY);
          recY += splitText.length * 6; // Adjust line spacing
          
          // Add new page if content is too long
          if (recY > 280) {
            doc.addPage();
            recY = 20;
          }
        });
      }

      // Footer (NO EMOJIS)
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text(t.footer, 20, pageHeight - 20);
      doc.text(`${t.reportId} ${Date.now()}`, 20, pageHeight - 10);

      // Save the PDF
      const fileName = `crop_report_${language}_${resultData.crop_name || 'analysis'}_${currentDate.replace(/\//g, '-')}.pdf`;
      doc.save(fileName);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating PDF report. Please try again.');
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-md p-6 border border-gray-200">
      <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center gap-2">
        📄 Generate Report
      </h3>
      <p className="text-gray-600 mb-6 text-sm">
        Download your crop analysis as a professional PDF report for record-keeping or sharing.
      </p>
      
      {/* Language Selection
      <div className="mb-4">
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Report Language / रिपोर्ट की भाषा:
        </label>
        <div className="flex gap-3">
          <button
            onClick={() => setLanguage('english')}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              language === 'english' 
                ? 'bg-blue-600 text-white' 
                : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
            }`}
          >
            English
          </button>
          <button
            onClick={() => setLanguage('hindi')}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              language === 'hindi' 
                ? 'bg-blue-600 text-white' 
                : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
            }`}
          >
            हिंदी (Hindi)
          </button>
        </div>
      </div> */}
      
      <button
        onClick={generatePDFReport}
        className="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors font-medium shadow-md"
      >
        📑 Download PDF Report ({language === 'english' ? 'English' : 'हिंदी'})
      </button>
      
      <div className="mt-4 text-xs text-gray-500">
        <p>• Professional formatted report with all analysis data</p>
        <p>• Includes farm details, weather conditions, predictions & recommendations</p>
        <p>• Available in English and Hindi languages</p>
        <p>• Suitable for agricultural records and compliance</p>
      </div>
    </div>
  );
};

export default ReportGenerator;